services:
  ndc-ollama:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./config:/etc/connector:ro
    environment:
      OLLAMA_SERVER_URL: ${OLLAMA_SERVER_URL}
      OLLAMA_TIMEOUT: "${OLLAMA_TIMEOUT}"
      HASURA_LOG_LEVEL: debug

  ollama:
    build:
      context: test/ollama
      dockerfile: Dockerfile
    ports:
      - 11434:11434
