# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-rest-schema/main/jsonschema/convert-config.jsonschema
file: https://raw.githubusercontent.com/ollama/ollama/bfff252fa936f3a23380aae3e75debc8b1d70c4c/specs/openapi-3.1.yaml
spec: oas3
envPrefix: OLLAMA
patchBefore:
  - path: patch-before.yaml
    strategy: json6902
